security:
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Usager
                property: email
    role_hierarchy:
        ROLE_ADMIN: ROLE_CLIENT
    encoders:
        App\Entity\Usager:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout: 
                path: app_logout
                target: home_page
    access_control:
        - { path: ^/(%app.supported_locales%)/admin, roles: ROLE_ADMIN }
        - { path: ^/(%app.supported_locales%)/usager/accueil, roles: ROLE_CLIENT }
        - { path: ^/(%app.supported_locales%)/usager/commandes, roles: ROLE_CLIENT }
